error

diff --git a/winenv b/winenv
--- a/winenv
+++ b/winenv
@@ -22,21 +22,30 @@ STEAM_COMPAT_CLIENT_INSTALL_PATH=${STEAM_COMPAT_CLIENT_INSTALL_PATH:-$HOME/.loca
 #
 # output $1 to stderr and exit if $2
 #
-function error {
-# colors
+function error {    
+    # colors
     local RED='\033[0;31m'
     local YELLOW='\033[1;33m'
     local LIGHT_BLUE='\033[1;34m'
-    local NOCOLOR='\033[0m' # No Color
+    local LIGHT_GREEN='\033[1;32m'
+    local NOCOLOR='\033[0m' # No Color    
     local COLOR=$NOCOLOR
-    if ! [ -z "$2" ]; then
-        COLOR=$RED
+    pfx="$LIGHT_GREEN${SELF_NAME^}:"
+    if [ ! -z "$2" ] ;then
+        if [ $2 -gt 0 ];then 
+            COLOR=$RED # if exit code > 0
+            pfx+="${YELLOW}${FUNCNAME[0]}:${FUNCNAME[1]}: "
+        else
+            pfx+="${LIGHT_BLUE}${FUNCNAME[1]}: "
+            COLOR=$YELLOW
+        fi    
     else
-        COLOR=$YELLOW
+        pfx+="${YELLOW}${FUNCNAME[1]}: "
+        COLOR=$LIGHT_BLUE
     fi
-    echo -e "${COLOR}$1${NOCOLOR}">&2
-    if ! [ -z "$2" ]; then
-     exit $2
+    echo -e "$pfx${COLOR}$1${NOCOLOR}">&2
+    if ! [ -z "$2" ] ; then    
+     exit $2 # if exist code , exit
     fi
 }
 #
