colors

diff --git a/winenv b/winenv
--- a/winenv
+++ b/winenv
@@ -16,10 +16,21 @@ _name="$_dir/$name"
 url="https://github.com/D10221/$name"
 fetch="https://raw.githubusercontent.com/D10221/$name/main/$name"
 desc='Sets env vars and paths to help run an arbitrary command on steam wine/proton app prefixes'
-#
+# colors
+RED='\033[0;31m'
+YELLOW='\033[1;33m'
+LIGHT_BLUE='\033[1;34m'
+NC='\033[0m' # No Color
+# error
 function error {
-    echo $1>&2
-    exit $2
+    c=$NC
+    if ! [ -z "$2" ]; then
+        c=$RED
+    else
+        c=$YELLOW
+    fi
+    echo -e "${c}$1">&2
+    ! [ -z "$2" ] && exit $2
 }
 # usage
 if [ -z "$1" ]; then
@@ -100,7 +111,7 @@ update)
     elif [[ "$new_version" > "$version" ]]; then
         bakd="$HOME/.local/share/$name"
         bak="$bakd/$name.$version.bak"
-        mkdir -p "$bakd" && cp "$_name" "$bak" && cat "$tmp" >"$_name" && echo "Updated: see backup at $bak" && exit 0 || echo "error updating" && exit 1
+        mkdir -p "$bakd" && cp "$_name" "$bak" && cat "$tmp" >"$_name" && error "Updated: see backup at $bak" 0 || error "error updating" 1
     fi
     exit
     ;;
@@ -140,29 +151,25 @@ APPID=$1;shift
 # if $APPID is not a number
 re='^[0-9]+$'
 if ! [[ $APPID =~ $re ]]; then
-ID_SEARCH=$APPID && echo "'$APPID' is not a number, searching for appid.">&2  && APPID=$(echo $appmanifest | jq --arg N $APPID '.[]|select(.name|test($N;"i"))|.appid') \
+ID_SEARCH=$APPID && error "'$APPID' is not a number, searching for appid." && APPID=$(echo $appmanifest | jq --arg N $APPID '.[]|select(.name|test($N;"i"))|.appid') \
 && [[ $APPID =~ $re ]] \
 && echo found APPID=$APPID >&2 \
 || error "Can't find app id for '$ID_SEARCH', search result '$APPID 'is not a number" 1
 fi
-
 # By ID
 appmanifest_by_id=$(get_appmanifest_by_id $APPID)
 APP_MANIFEST=$( echo $appmanifest_by_id |jq '.appmanifest' |tr -d \")
 APP_DIR=$( echo $appmanifest_by_id |jq '.libraryfolder+"/steamapps/common/"+.installdir')
-
 # STEAM_COMPAT_DATA_PATH
 STEAM_COMPAT_DATA_PATH=$(echo $appmanifest_by_id| jq --arg id $APPID '.libraryfolder+"/steamapps/compatdata/"+$id'|tr -d \")
 if [ ! -d "$STEAM_COMPAT_DATA_PATH" ]; then
     error "STEAM_COMPAT_DATA_PATH='$STEAM_COMPAT_DATA_PATH' is not a directory" 1
 fi
-
 #  wine prefix
 WINEPREFIX="$STEAM_COMPAT_DATA_PATH/pfx"
 if [ ! -d "$WINEPREFIX" ]; then
     error "WINEPREFIX=$WINEPREFIX is not a directory" 1    
 fi
-
 #  Compat tool Version
 COMPAT_TOOL_VERSION=$(cat $STEAM_COMPAT_DATA_PATH/version)
 if [ -z "$COMPAT_TOOL_VERSION" ]; then
