args

diff --git a/winenv b/winenv
--- a/winenv
+++ b/winenv
@@ -19,9 +19,9 @@ SELF_DESC='Sets env vars and paths to help run an arbitrary command on steam win
 SELF_INSTALL_TARGET="$HOME/.local/bin/$SELF_NAME"
 # VARS
 STEAM_COMPAT_CLIENT_INSTALL_PATH=${STEAM_COMPAT_CLIENT_INSTALL_PATH:-$HOME/.local/share/Steam}
-# 
+#
 # output $1 to stderr and exit if $2
-# 
+#
 function error {
 # colors
     local RED='\033[0;31m'
@@ -33,7 +33,7 @@ function error {
         COLOR=$RED
     else
         COLOR=$YELLOW
-    fi    
+    fi
     echo -e "${COLOR}$1${NOCOLOR}">&2
     if ! [ -z "$2" ]; then
      exit $2
@@ -43,19 +43,19 @@ function error {
 function get_appmanifests
 {
     local libraryfolders=$STEAM_COMPAT_CLIENT_INSTALL_PATH/config/libraryfolders.vdf
-    if ! [ -f "$libraryfolders" ];then 
+    if ! [ -f "$libraryfolders" ];then
         error "libraryfolders=$libraryfolders is not a file" 1
     fi
     read -d "\n" -ra _folders <<<"$(cat $libraryfolders | vdf2json|jq '.libraryfolders[].path? ' )"
     for libraryfolder in "${_folders[@]}"; do
         libraryfolder=$(echo $libraryfolder|tr -d \") # remove quotes
-        entries=$(ls $libraryfolder/steamapps/appmanifest_*.acf)  
+        entries=$(ls $libraryfolder/steamapps/appmanifest_*.acf)
         read -d " "  -ra _entries <<<$entries
         for appmanifest in "${_entries[@]}"; do
             manifest=$(cat $appmanifest | vdf2json | jq )
             args="--arg libraryfolder $libraryfolder --arg appmanifest $appmanifest"
             echo $manifest | jq $args '.AppState | {name,appid,installdir,libraryfolder:$libraryfolder, appmanifest:$appmanifest}'
-        done    
+        done
     done
 }
 #
@@ -63,7 +63,7 @@ function get_app_id_by_name ()
 {
     echo $1 | jq --arg N $2 '.[]|select(.name|test($N;"i"))|.appid'
 }
-function get_appmanifest_by_id 
+function get_appmanifest_by_id
 {
     echo $1 |jq --argjson id $2 '.[]| select(.appid==$id)'
 }
@@ -73,12 +73,12 @@ function maybe_app_id (){
     local APPID_REGEX='^[0-9]+$'
     local APPID=$1
     if ! [[ $APPID =~ $APPID_REGEX ]]; then
-        ID_SEARCH=$APPID 
-        error "'$APPID' is not an ID searching for app id by name like '$APPID'"        
-        APPID=$(get_app_id_by_name "$appmanifest" "$ID_SEARCH")         
-        if ! [[ $APPID =~ $APPID_REGEX ]]; then    
+        ID_SEARCH=$APPID
+        error "'$APPID' is not an ID searching for app id by name like '$APPID'"
+        APPID=$(get_app_id_by_name "$appmanifest" "$ID_SEARCH")
+        if ! [[ $APPID =~ $APPID_REGEX ]]; then
             error "Can't find app id for '$ID_SEARCH', search result '$APPID 'is not an app id." 1
-        fi    
+        fi
     fi
     echo $APPID
 }
@@ -91,7 +91,7 @@ function showenv ()
         if [ ! -z "$i" ]; then
             echo ${i/export /''}
         fi
-    done    
+    done
 }
 #
 # show info in json format for givev $1="app id or name" f
@@ -99,15 +99,23 @@ function showenv ()
 function show_info (){
     local appmanifest=$(get_appmanifests | jq -s)
     if [ -z "$1" ]; then
-        echo $appmanifest    
-    else        
+        echo $appmanifest
+    else
         local APPID
         APPID=$(maybe_app_id $1) && echo $(get_appmanifest_by_id "$appmanifest" "$APPID")
     fi
 }
 function show_id ()
 {
-    echo $(get_app_id_by_name "$(get_appmanifests | jq -s)" $1)
+    if [ -z "$1" ];then 
+         error "name required" 1
+    fi
+    local APPID=''
+    APPID=$(get_app_id_by_name "$(get_appmanifests | jq -s)" $1)
+    if [ -z "$APPID" ]; then
+        error "Not found" 1    
+    fi
+    echo $APPID
 }
 function usage(){
     echo "$SELF_NAME: v$SELF_VERSION $SELF_URL"
@@ -137,22 +145,19 @@ function get_version {
 # install into user/bin
 function self_install()
 {
-    if [ -f $SELF_INSTALL_TARGET ]; then
-        echo "$SELF_NAME is already installed" >&2
-        exit 1
-    fi
-    cp "$SELF_PATH" $SELF_INSTALL_TARGET
+    [ -f $SELF_INSTALL_TARGET ] \
+    && error "$SELF_NAME is already installed" 1 \
+    || cp "$SELF_PATH" "$SELF_INSTALL_TARGET" \
+    && echo "installed: '$SELF_INSTALL_TARGET'"
 }
-function self_uninstall () 
+# remove from user system
+function self_uninstall ()
 {
-    # remove from user system
-    if [ ! -f $SELF_INSTALL_TARGET ]; then
-        echo "$SELF_NAME is not installed" >&2
-        exit 1
-    fi
-    rm "$SELF_INSTALL_TARGET " -rf    
-    echo "get it from $SELF_URL"
+    rm "$SELF_INSTALL_TARGET" \
+    &&  echo "uninstalled: '$SELF_INSTALL_TARGET'" \
+    || error "$SELF_NAME is not installed" 1
 }
+#
 function self_update ()
 {
     # download new version
@@ -166,7 +171,7 @@ function self_update ()
         echo "error: can't udpate, see file: '$tmp' version ($new_version) is mayor than this version ($SELF_VERSION)"
         exit 1
     elif [[ "$new_version" == "$SELF_VERSION" ]]; then
-        echo "error: can't udpate, see file: '$tmp' version ($new_version) equals this ($SELF_VERSION)"        
+        echo "error: can't udpate, see file: '$tmp' version ($new_version) equals this ($SELF_VERSION)"
         exit 1
     elif [[ "$new_version" > "$SELF_VERSION" ]]; then
         local bakd="$HOME/.local/share/$SELF_NAME"
@@ -174,7 +179,7 @@ function self_update ()
         mkdir -p "$bakd" && cp "$SELF_PATH" "$bak" && cat "$tmp" >"$SELF_PATH" && error "Updated: see backup at $bak" 0 || error "error updating" 1
     fi
 }
-function main () 
+function main ()
 {
     # All Apps
     local appmanifest=$(get_appmanifests | jq -s)
@@ -182,7 +187,7 @@ function main ()
     local APPID
     APPID=$(maybe_app_id $1) || exit 1
     # App's manifest
-    local appmanifest_by_id=$(get_appmanifest_by_id "$appmanifest" "$APPID")    
+    local appmanifest_by_id=$(get_appmanifest_by_id "$appmanifest" "$APPID")
     #
     local APP_MANIFEST=$( echo $appmanifest_by_id |jq '.appmanifest' |tr -d \")
     #
@@ -197,12 +202,12 @@ function main ()
     #  wine prefix
     local WINEPREFIX="$STEAM_COMPAT_DATA_PATH/pfx"
     if [ ! -d "$WINEPREFIX" ]; then
-        error "WINEPREFIX=$WINEPREFIX is not a directory" 1    
+        error "WINEPREFIX=$WINEPREFIX is not a directory" 1
     fi
     #  Compat tool Version
     local COMPAT_TOOL_VERSION=$(cat $STEAM_COMPAT_DATA_PATH/version)
     if [ -z "$COMPAT_TOOL_VERSION" ]; then
-        error "Can't find COMPAT_TOOL_VERSION for APPID=$APPID with STEAM_COMPAT_DATA_PATH=$STEAM_COMPAT_DATA_PATH" 1    
+        error "Can't find COMPAT_TOOL_VERSION for APPID=$APPID with STEAM_COMPAT_DATA_PATH=$STEAM_COMPAT_DATA_PATH" 1
     fi
     # Compat tool path
     local COMPAT_TOOL_PATH="$STEAM_COMPAT_CLIENT_INSTALL_PATH/compatibilitytools.d/$COMPAT_TOOL_VERSION"
@@ -231,46 +236,65 @@ function main ()
     WINENV+="export STEAM_COMPAT_CLIENT_INSTALL_PATH=$STEAM_COMPAT_CLIENT_INSTALL_PATH &&"
     WINENV+="export PATH=$COMPAT_TOOL_PATH:$COMPAT_TOOL_PATH/files/bin:$PATH"
     # show env if no args left
-    if [ -z "$1" ]; then
-    showenv "$WINENV" && exit
-    fi
-    # run
-    cmd="$WINENV && $1"
-    # echo cmd="$cmd"
-    bash -c "$cmd" 
+    if [ -z "$2" ]; then
+        showenv "$WINENV" 
+    else 
+        # run
+        cmd="$WINENV && $2"
+        # echo cmd="$cmd"
+        bash -c "$cmd"
+    fi    
 }
 # Validate requirements
 if ! [ -d "$STEAM_COMPAT_CLIENT_INSTALL_PATH" ]; then
-error "STEAM_COMPAT_CLIENT_INSTALL_PATH=$STEAM_COMPAT_CLIENT_INSTALL_PATH is not a directory" 1
+    error "STEAM_COMPAT_CLIENT_INSTALL_PATH=$STEAM_COMPAT_CLIENT_INSTALL_PATH is not a directory" 1
 fi
 # process args
-case "${1}" in
+case "$1" in
     install)
-        self_install
-        exit 
+        shift;
+        (( $#  > 0 )) \
+        && error "Too many args" 1 \
+        || self_install \
+        && exit
         ;;
-    uninstall) 
-        self_uninstall
-        exit 
+    uninstall)
+        shift;
+        (( $#  > 0 )) \
+        && error "Too many args" 1 \
+        || self_uninstall
+        exit
         ;;
     update)
-        self_update
+        shift;
+        (( $#  > 0 )) \
+        && error "Too many args" 1 \
+        || self_update
         exit
         ;;
     info)
-        show_info $2
+        shift
+        (( $#  > 1 )) \
+        && error "Too many args" 1 \
+        || show_info $1
         exit
         ;;
     id)
-        show_id $2
+        shift
+        (( $# > 1 )) \
+        && error "Too many args" 1 \
+        || show_id $1
         exit
         ;;
     *)
         # usage when no args
-        if [ -z "$1" ]; then
-            usage
-            exit
+        if (( $# == 0 )) ; then
+            usage; exit
         fi        
-        main $@
+        if (( $# > 2 )) ; then
+            error "Too many args" 1
+        fi
+        main "$1" "$2"
+        exit
         ;;
 esac
