helpers, +APP_NAME

diff --git a/winenv b/winenv
--- a/winenv
+++ b/winenv
@@ -16,6 +16,8 @@ _name="$_dir/$name"
 url="https://github.com/D10221/$name"
 fetch="https://raw.githubusercontent.com/D10221/$name/main/$name"
 desc='Sets env vars and paths to help run an arbitrary command on steam wine/proton app prefixes'
+#
+APPID_REGEX='^[0-9]+$'
 # colors
 RED='\033[0;31m'
 YELLOW='\033[1;33m'
@@ -31,6 +33,38 @@ function error {
     fi
     echo -e "${COLOR}$1${NOCOLOR}">&2
     ! [ -z "$2" ] && exit $2
+}
+# 
+STEAM_COMPAT_CLIENT_INSTALL_PATH=${STEAM_COMPAT_CLIENT_INSTALL_PATH:-$HOME/.local/share/Steam} \
+&& ! [ -d "$STEAM_COMPAT_CLIENT_INSTALL_PATH" ] \
+&& error "STEAM_COMPAT_CLIENT_INSTALL_PATH=$STEAM_COMPAT_CLIENT_INSTALL_PATH is not a directory" 1
+#
+libraryfolders=$STEAM_COMPAT_CLIENT_INSTALL_PATH/config/libraryfolders.vdf \
+&& ! [ -f "$libraryfolders" ] \
+&& error "libraryfolders=$libraryfolders is not a file" 1
+#
+function get_appmanifests
+{
+    read -d "\n" -ra _folders <<<"$(cat $libraryfolders | vdf2json|jq '.libraryfolders[].path? ' )"
+for libraryfolder in "${_folders[@]}"; do
+    libraryfolder=$(echo $libraryfolder|tr -d \") # remove quotes
+    entries=$(ls $libraryfolder/steamapps/appmanifest_*.acf)  
+    read -d " "  -ra _entries <<<$entries
+    for appmanifest in "${_entries[@]}"; do
+        manifest=$(cat $appmanifest | vdf2json | jq )
+        args="--arg libraryfolder $libraryfolder --arg appmanifest $appmanifest"
+        echo $manifest | jq $args '.AppState | {name,appid,installdir,libraryfolder:$libraryfolder, appmanifest:$appmanifest}'
+    done    
+done
+}
+#
+function get_app_id_by_name ()
+{
+    echo $1 | jq --arg N $2 '.[]|select(.name|test($N;"i"))|.appid'
+}
+function get_appmanifest_by_id 
+{
+    echo $1 |jq --argjson id $2 '.[]| select(.appid==$id)'
 }
 # usage
 if [ -z "$1" ]; then
@@ -121,45 +155,46 @@ update-config)
     echo "$cfg_global"
     exit
     ;;
+appmanifest)
+    appmanifest=$(get_appmanifests | jq -s)
+    if [ -z "$2" ]; then
+        echo $appmanifest    
+    else
+        if [[ $2 =~ $APPID_REGEX ]]; then
+            APPID=$2
+        else            
+            APPID=$(get_app_id_by_name "$appmanifest" "$2")                 
+        fi                
+        echo $(get_appmanifest_by_id "$appmanifest" "$APPID")
+    fi
+    exit
+    ;;
+appid)
+    echo $(get_app_id_by_name "$(get_appmanifests | jq -s)" $2)
+    exit
+    ;;
 esac
-# All Installed apps manifests
-libraryfolders=$STEAM_COMPAT_CLIENT_INSTALL_PATH/config/libraryfolders.vdf
-#
-function get_appmanifests
-{
-    read -d "\n" -ra _folders <<<"$(cat $libraryfolders | vdf2json|jq '.libraryfolders[].path? ' )"
-for libraryfolder in "${_folders[@]}"; do
-    libraryfolder=$(echo $libraryfolder|tr -d \") # remove quotes
-    entries=$(ls $libraryfolder/steamapps/appmanifest_*.acf)  
-    read -d " "  -ra _entries <<<$entries
-    for appmanifest in "${_entries[@]}"; do
-        manifest=$(cat $appmanifest | vdf2json | jq )
-        args="--arg libraryfolder $libraryfolder --arg appmanifest $appmanifest"
-        echo $manifest | jq $args '.AppState | {name,appid,installdir,libraryfolder:$libraryfolder, appmanifest:$appmanifest}'
-    done    
-done
-}
-#
+# All Apps
 appmanifest=$(get_appmanifests | jq -s)
 #
-function get_appmanifest_by_id 
-{
-    echo $appmanifest |jq --argjson id "$1" '.[]| select(.appid==$id)'
-}
-#
 APPID=$1;shift
-# if $APPID is not a number
-re='^[0-9]+$'
-if ! [[ $APPID =~ $re ]]; then
-ID_SEARCH=$APPID && error "'$APPID' is not a number, searching for appid." && APPID=$(echo $appmanifest | jq --arg N $APPID '.[]|select(.name|test($N;"i"))|.appid') \
-&& [[ $APPID =~ $re ]] \
-&& echo found APPID=$APPID >&2 \
-|| error "Can't find app id for '$ID_SEARCH', search result '$APPID 'is not a number" 1
+# if $APPID is not a number, serach app id by name
+if ! [[ $APPID =~ $APPID_REGEX ]]; then
+    ID_SEARCH=$APPID 
+    error "'$APPID' is not an ID searching for app id by name."
+    APPID=$(get_app_id_by_name "$appmanifest" "$ID_SEARCH") 
+    if ! [[ $APPID =~ $APPID_REGEX ]]; then    
+        error "Can't find app id for '$ID_SEARCH', search result '$APPID 'is not an app id." 1
+    fi    
 fi
-# By ID
-appmanifest_by_id=$(get_appmanifest_by_id $APPID)
+# App's manifest
+appmanifest_by_id=$(get_appmanifest_by_id "$appmanifest" "$APPID")
+#
 APP_MANIFEST=$( echo $appmanifest_by_id |jq '.appmanifest' |tr -d \")
+#
 APP_DIR=$( echo $appmanifest_by_id |jq '.libraryfolder+"/steamapps/common/"+.installdir' | tr -d \")
+#
+APP_NAME=$( echo $appmanifest_by_id |jq '.name')
 # STEAM_COMPAT_DATA_PATH
 STEAM_COMPAT_DATA_PATH=$(echo $appmanifest_by_id| jq --arg id $APPID '.libraryfolder+"/steamapps/compatdata/"+$id'|tr -d \")
 if [ ! -d "$STEAM_COMPAT_DATA_PATH" ]; then
@@ -193,6 +228,7 @@ fi
 # exports
 WINENVx="export APPID=$APPID &&"
 WINENV+="export APP_DIR="$APP_DIR" &&"
+WINENV+="export APP_NAME="$APP_NAME" &&"
 WINENV+="export APP_MANIFEST=$APP_MANIFEST &&"
 WINENV+="export WINEPREFIX=$WINEPREFIX &&"
 WINENV+="export WINE=$WINE &&"
